### ISSUE TITLE
'VerifyError' when running DaCapo benchmark xalan

### ISSUE THREAD

**Issue by greatmazinger** [ElephantTracksProject/et2-java#13]
Running the DaCapo benchmark xalan with the following command:

`java -agentpath:./libet2.so  -jar dacapo-9.12-bach.jar xalan -t 1`

results in the following output:
```
Parsing java/io/FileNotFoundException was successful
Parsing java/io/IOException was successful
Parsing java/lang/VerifyError was successful
Exception in thread "main" Parsing java/lang/Throwable$WrappedPrintStream was successful
Parsing java/lang/Throwable$PrintStreamOrWriter was successful
java.lang.VerifyError: (class: org/dacapo/harness/TestHarness, method: <init> signature: (Ljava/io/InputStream;)V) Expecting to find object/array on stack
        at Harness.main(Harness.java)
```

**Comment by greatmazinger** [comment]
Looks like this is a verification error by the bytecode verifier. Turning off the verification by -noverify allows the parsing to go on, but obviously this needs to be fixed.

**Comment by xuanruiqi** [comment]
This has been a long standing issue in Elephant Tracks II. The dirty fix is to use `-noverify` to keep it going on for a while, but I'm not sure what is exactly causing the problem.

I can also help look into this issue. Maybe we can dump the bytecode or something and look for what's going wrong?

**Comment by greatmazinger** [comment]
Yeah, unfortunately this results in a SIGSEGV for DaCapo xalan:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fd0464ebe61, pid=25438, tid=0x00007fd045977700
#
# JRE version: OpenJDK Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x643e61]
#
# Core dump written. Default location: /data/rveroy/pulsrc/DACAPO/core or core.25438 (max size 1536 kB). To ensure a full core dump, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /data/rveroy/pulsrc/DACAPO/hs_err_pid25438.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

Do you think we're perturbing the stack and leaving it in a corrupted state?

**Comment by xuanruiqi** [comment]
It could be. I suppose the best way to debug is to build a debug version of OpenJDK 8 and use {debug, profiling} tools on it. I'm not sure this will work, but at least we could try.

**Comment by greatmazinger** [comment]
I've been trying some things. It seems that the verification error output in Java 11 is better than it is in Java 1.8. This is the verification error running on a [mini benchmark I created using the H2 database](https://github.com/greatmazinger/h2bmark) while using Java 11:

```
Error: Unable to initialize main class net.veroy.research.H2Bmark
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/veroy/research/H2Bmark.main([Ljava/lang/String;)V @91: invokestatic
  Reason:
    Type uninitialized 53 (current frame, stack[3]) is not assignable to 'java/lang/Object'
  Current Frame:
    bci: @91
    flags: { }
    locals: { '[Ljava/lang/String;', 'java/lang/String', 'java/sql/Connection', 'java/sql/Statement', 'java/lang/String', top, top, uninitialized 53, 'java/io/FileReader' }
    stack: { uninitialized 53, uninitialized 53, 'java/io/FileReader', uninitialized 53, integer, integer }
  Bytecode:
    0000000: 1300 9301 b800 7512 024c 2b12 0304 b800
    0000010: 0412 05b8 0006 572b ba00 0700 00b8 0008
    0000020: 4d2c b900 0901 004e 2d12 0ab9 000b 0200
    0000030: 5712 0c3a 04bb 000d 593a 0759 bb00 0e59
    0000040: 3a08 5919 04b7 000f 1908 1300 9713 0096
    0000050: b800 8119 0713 0095 1300 94b8 0081 b700
    0000060: 10b6 0011 3a05 2db9 0012 0100 2cb9 0013
    0000070: 0100 1300 93b8 0079 b1
```

**Comment by xuanruiqi** [comment]
I think I mildly know what the problem is. There might have been a bug in instrumenting object allocation (and all allocated objects are initially uninitialized). I think I did not fix the bug because I can't think of a way to get around it (e.g. delaying instrumentation until object is fully initialized). Also, IIRC, we can't use the ET1 solution because that one requires going through the JNI abstraction boundary, which defeats the entire purpose of ET2. So this is still a problem we need to solve.

**Comment by greatmazinger** [comment]
Closing as I'm moving ET2 to ASM.
