### ISSUE TITLE
Performance issues when running ET2 on non-trivial programs

### ISSUE THREAD

**Issue by greatmazinger** [ElephantTracksProject/et2-java#14]
Running ET2 with `-noverify` to avoid the [verification error](https://github.com/ElephantTracksProject/et2-java/issues/13) takes a long time to load classes for non-trivial programs. The program I'm running is [an H2 benchmark that comes with the H2 distribution](http://h2database.com/html/main.html).

**Comment by xuanruiqi** [comment]
I've noticed the same problem: while it makes small programs faster, ET2 currently suffers from performance bugs on large programs which I don't know how to explain. Maybe some profiling will help.

**Comment by greatmazinger** [comment]
Do you know how to profile and/or debug agent code? Haven't looked it up yet.

**Comment by xuanruiqi** [comment]
I don't, but I suspect we can have profiling tools only profile calls within a certain shared library.

**Comment by greatmazinger** [comment]
Closing as I'm moving ET2 to ASM.
