### ISSUE TITLE
Doesn't moving ET2 to asm "defeat the purpose" of ET2?

### ISSUE THREAD

**Issue by xuanruiqi** [ElephantTracksProject/et2-java#15]
Unless it's changed now, ASM is still a Java library, so you'd use IPC to do bytecode rewriting. One of the main goals of the design of ET2 was to get rid of these expensive IPCs. I have not benchmarked anything, but it seems that if we switch back to ASM we will lose all of the potential performance gains...

**Comment by xuanruiqi** [comment]
Unless we can now do rewriting inside of the host JVM, that is to say.

**Comment by greatmazinger** [comment]
Yeah, I'm trying out the j[ava.lang.instrument / -javaagent way](https://docs.oracle.com/javase/8/docs/api/java/lang/instrument/package-summary.html) of using ASM. That is, there's not need to spin up a separate JVM. So far the prototype instrumenter is working. There are a few issues that need to be solved.

**Comment by xuanruiqi** [comment]
I see, that seems like a more stable solution, especially as JNIF development/bug fix is very slow.

**Comment by xuanruiqi** [comment]
I've looked into java.lang.instrument a bit, and I might know some things. Would be glad to help (too busy this month though).

**Comment by greatmazinger** [comment]
Yeah, I ran into situations where debugging the exceptions JNIF was throwing was difficult.

**Comment by greatmazinger** [comment]
Cool if you have the time. I'll just open issues and things to do as I find them. :)
