### ISSUE TITLE
Final flush

### ISSUE THREAD

**Issue by ghost** [ElephantTracksProject/et2-java#2]
In ETProxy.java, flushBuffer always loops 1000 times. However, the final flush might have less than 1000 events to emit.

**Comment by xuanruiqi** [comment]
Good point. Will fix ASAP.

**Comment by xuanruiqi** [comment]
I figured out that there's another problem. I didn't yet implement the "final flush" yet...

I'll try implementing this via a JVMTI callback.

**Comment by greatmazinger** [comment]
The final buffer write leaves at least one incomplete event at the end. Given the situation regarding the buffer flushing, there are probably more events that were not written out.

**Comment by greatmazinger** [comment]
Implemented the final flush using Runtime shutdown hook.
