### ISSUE TITLE
Null check in callback

### ISSUE THREAD

**Issue by ghost** [ElephantTracksProject/et2-java#3]
In Callbacks.cc, class_name passed to the onClassFileLoad method can be null. Need to be careful when calling string(class_name).

**Comment by xuanruiqi** [comment]
Good catch. Looking into it.

**Comment by xuanruiqi** [comment]
Fixed. Meanwhile I fixed it by just returning from the function (because I don't yet know what can result in `class_name` being null). Maybe we should also (or instead) throw an exception/signal an error.
