### ISSUE TITLE
Issue when writing traces

### ISSUE THREAD

**Issue by leandrohw** [ElephantTracksProject/et2-java#4]
I ran ET2 with this minimal example: public class Test1 {public static void main(String[] args) {} }

When I look at the traces, it seems that some of them get printed on the same line. It looks like there are empty lines and W with a single value too.

cat trace |sort | uniq -c | sort -nr
  16653 W 507301368 30 896148557
   1963 M 85 507301368 896148557
   1962 E 85 896148557
    982 M 95 507301368 896148557
    982 M 94 507301368 896148557
    982 M 104 507301368 896148557
    981 M 96 507301368 896148557
    981 E 96 896148557
    981 E 95 896148557
    981 E 94 896148557
    981 E 114 896148557
    981 E 106 896148557
    980 M 106 507301368 896148557
    980 E 104 896148557
    971 M 114 507301368 896148557
     11 
      5 W 507301368 30 896148557W 507301368 30 896148557
      4 M 507 0 896148557
      4 M 506 0 896148557
      4 E 507 896148557
      4 E 506 896148557
      2 N 2056308395 16 121 404 0 896148557
      2 N 1066553149 16 121 403 0 896148557
      2 M 505 0 896148557
      2 M 504 0 896148557
      2 M 502 0 896148557
      2 M 498 0 896148557
      2 E 505 896148557
      2 E 504 896148557
      2 E 502 896148557
      2 E 498 896148557
      2 E 473 1442407170
      2 A 1001245840 56 122 405 10 896148557
      1 W 507301368 30 896148557M 473 0 1442407170
      1 W 507301
      1 M 85 507301368 896148557W 507301368 30 896148557
      1 M 473 0 1442407170
      1 M 114 507301368 896148557W 507301368 30 896148557
      1 M 106 507301368 896148557W 507301368 30 896148557
      1 E 85 896148557W 507301368 30 896148557
      1 E 104 896148557W 507301368 30 896148557

**Comment by xuanruiqi** [comment]
I am aware of this bug. While I did do proper synchronization with mutexes, this issue persists. Looking into what's wrong here.

**Comment by xuanruiqi** [comment]
Insight: instead of using plain locks, we might need to use semaphores to count the # of threads waiting.

Consider this code segment:

	mutex.lock();
    ...print stuff
    mutex.unlock();

if two threads lock at the same time, that might be a problem. If we have a semaphore counting the # of threads which gets released only at 0 (or something), the problem might get fixed.

**Comment by greatmazinger** [comment]
This looks complex. What is the current status of this? @xuanruiqi

**Comment by xuanruiqi** [comment]
Honestly speaking, I have not looked at ET2 since I finished up my thesis draft. I still think the semaphore solution is worth trying, but maybe someone has to implement that.

**Comment by greatmazinger** [comment]
Closing as I'm moving ET2 to ASM library.
