### ISSUE TITLE
Duplicated trace event entries

### ISSUE THREAD

**Issue by leandrohw** [ElephantTracksProject/et2-java#5]
Here's the example I ran.

> public class Test2 {
>   public static void main(String[] args) {
>     for (int i = 0; i < 10; i++) {
>       print_hello();
>     }
>   }
> 
>   static void print_hello() {
>     System.out.println("Hello World");
>   }
> }
> 

In the methods.list, I have this row:

474, Test2, print_hello

When I check the trace file, print_hello has 20 entries for M and 20 for E. I believe they should have been 10 each.

17162 W 1548658949 30 1765964249
   2025 M 85 1548658949 1765964249
   2012 E 85 1765964249
   1012 M 94 1548658949 1765964249
   1012 M 114 1548658949 1765964249
   1012 M 104 1548658949 1765964249
   1012 E 114 1765964249
   1011 M 96 1548658949 1765964249
   1011 M 95 1548658949 1765964249
   1011 M 106 1548658949 1765964249
   1011 E 96 1765964249
   1011 E 95 1765964249
   1011 E 94 1765964249
   1011 E 106 1765964249
   1011 E 104 1765964249
     **20 M 474 0 1442407170
     20 E 474 1442407170**
     10 
      7 W 1548658949 30 1765964249W 1548658949 30 1765964249
      4 M 508 0 1765964249
      4 M 507 0 1765964249
      3 E 508 1765964249
      3 E 507 1765964249
      2 N 1673138857 16 121 403 0 1765964249
      2 M 506 0 1765964249
      2 M 473 0 1442407170
      2 E 473 1442407170
      2 A 1736804993 56 122 405 10 1765964249
      1 N 649625786 16 121 404 0 1765964249
      1 M 95 1548658949 1765964249W 1548658949 30 1765964249
      1 M 505 0 1765964249
      1 M 503 0 1765964249
      1 M 499 0 1765964249
      1 E 96 1765964249W 1548658949 30 1765964249
      1 E 85 1765964249W 1548658949 30 1765964249
      1 E 506 1765964249
      1 E 505 1765964249
      1 E 503 1765964249
      1 E 499 1765964249
      1 E 106 1765964249W 1548658949 30 1765964249

**Comment by xuanruiqi** [comment]
This is really weird. Looking into this.

**Comment by greatmazinger** [comment]
Likewise, is this still an issue? @leandrohw  @xuanruiqi

**Comment by xuanruiqi** [comment]
Still an issue.

**Comment by greatmazinger** [comment]
Closing as I'm moving ET2 to the ASM bytecode instrumentation library.
