### ISSUE TITLE
Timestamp all parameters

### ISSUE THREAD

**Issue by xuanruiqi** [ElephantTracksProject/et2-java#6]
From meeting records

**Comment by greatmazinger** [comment]
@xuanruiqi What does it mean to timestamp all parameters?

**Comment by xuanruiqi** [comment]
We would want to give all method parameters a timestamp, as this would be useful for our modified death time algorithm.

**Comment by greatmazinger** [comment]
Closing this for now as I'm moving ET2 to the ASM bytecode instrumentation library.
