### ISSUE TITLE
Build dependency on jnif is hardcoded to xuanrui's home directory

### ISSUE THREAD

**Issue by greatmazinger** [ElephantTracksProject/et2-java#7]
This needs to be more portable. From a preliminary search, I'm guessing jnif is http://sape.inf.usi.ch/jnif.

**Comment by greatmazinger** [comment]
Saw the documentation about JNIF and that we have [a fork of it here](https://github.com/ElephantTracksProject/jnif). The question is: how has [the main repo of JNIF](https://gitlab.com/acuarica/jnif) diverged from our fork?

**Comment by xuanruiqi** [comment]
IIRC, we changed a few places that caused problems for ET2. I have not pulled from upstream since we forked.

**Comment by greatmazinger** [comment]
Fixed in commit 930200bbb2e1a536c2aece6d3cf41ac3455a9981
