### ISSUE TITLE
Documentation for flushBuffer in ETProxy seems to be inconsistent with the variable names

### ISSUE THREAD

**Issue by greatmazinger** [ElephantTracksProject/et2-java#9]
Examples:
* [Line 523](https://github.com/ElephantTracksProject/et2-java/blob/master/ETProxy.java#L523)
* [Line 536](https://github.com/ElephantTracksProject/et2-java/blob/master/ETProxy.java#L536)

**Comment by xuanruiqi** [comment]
Maybe a bug. I'll look at the code to determine which one is correct.

**Comment by greatmazinger** [comment]
Closing as I'm moving ET2 to ASM.
